language: node_js
node_js:
  - '12'
dist: bionic

branches:
  only:
    - master

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

jobs:
  include:
    # - stage: 'Tests'
    #   name: 'Unit Tests'
    #   script: ng test --watch=false --browsers=ChromeHeadless
    - stage: 'Build'
      name: 'Production Build'
      script: ng build --prod
