language: node_js
node_js:
- '12'
dist: bionic
branches:
  only:
  - master
addons:
  chrome: stable
  ssh_known_hosts:
  - ded.scrollingtext.org
cache:
  directories:
  - "./node_modules"
install:
- npm install
jobs:
  include:
  - stage: Build
    name: Production Build
    script: ng build --prod

before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after $TRAVIS_BUILD_DIR/dist/DED/ alex@ded.scrollingtext.org:~/test/
  on:
    branch: master

